"""Add bandwidth_bytes to buckets

Revision ID: 0dd4a51b0e60
Revises: 736f5c7ad281
Create Date: 2026-04-16 21:04:14.670155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd4a51b0e60'
down_revision: Union[str, Sequence[str], None] = '736f5c7ad281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###
