"""Add Haystack columns to files table

Revision ID: 52c1aac2be82
Revises: 6f01bae36aa6
Create Date: 2026-05-10 21:23:06.076430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c1aac2be82'
down_revision: Union[str, Sequence[str], None] = '6f01bae36aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status', sa.String(length=20), nullable=False, server_default='uploading'))
    op.add_column('files', sa.Column('volume_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('offset', sa.Integer(), nullable=True))
    op.drop_column('files', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('files', 'offset')
    op.drop_column('files', 'volume_id')
    op.drop_column('files', 'status')
    # ### end Alembic commands ###
