"""added queued_message table

Revision ID: 6f01bae36aa6
Revises: e9076dea3b48
Create Date: 2026-04-24 11:46:31.409444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f01bae36aa6'
down_revision: Union[str, Sequence[str], None] = 'e9076dea3b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queued_messages')
    # ### end Alembic commands ###
