"""Advanced billing and soft delete

Revision ID: e9076dea3b48
Revises: 0dd4a51b0e60
Create Date: 2026-04-16 21:15:26.319059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9076dea3b48'
down_revision: Union[str, Sequence[str], None] = '0dd4a51b0e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('current_storage_bytes', sa.Integer(), nullable=False))
    op.add_column('buckets', sa.Column('ingress_bytes', sa.Integer(), nullable=False))
    op.add_column('buckets', sa.Column('egress_bytes', sa.Integer(), nullable=False))
    op.add_column('buckets', sa.Column('internal_transfer_bytes', sa.Integer(), nullable=False))
    op.drop_column('buckets', 'bandwidth_bytes')
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_deleted')
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.INTEGER(), nullable=False))
    op.drop_column('buckets', 'internal_transfer_bytes')
    op.drop_column('buckets', 'egress_bytes')
    op.drop_column('buckets', 'ingress_bytes')
    op.drop_column('buckets', 'current_storage_bytes')
    # ### end Alembic commands ###
